version: '3.4'

networks:
  sample-network:

services:
      
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: AHSB93993
    ports:
      - 27017:27017
    networks:
      - sample-network

  mongo-express:
    image: mongo-express
    container_name: mongo-manager
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: AHSB93993
    depends_on:
      - mongo
    networks:
      - sample-network